"[]":
  display: opaque

"[type=dirt]":
  display_name: Dirt
  top: grass_top
  side: grass_side
  bottom: grass_bottom
  
"[type=basalt]":
  display_name: Basalt
  
"[type=clay]":
  display_name: Clay
  
"[type=silt]":
  display_name: Silt
  
"[type=grass]":
  display_name: Grass